// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YtDownloader.Infrastructure;


namespace YtDownloader.Infrastructure.Migrations;
[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

        modelBuilder.Entity("YtDownloader.Domain.DownloadJob", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("TEXT");

                b.Property<long?>("CompletedAt")
                    .HasColumnType("INTEGER");

                b.Property<long>("CreatedAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(2000)
                    .HasColumnType("TEXT");

                b.Property<long?>("ExpiresAt")
                    .HasColumnType("INTEGER");

                b.Property<string>("FilePath")
                    .HasMaxLength(4096)
                    .HasColumnType("TEXT");

                b.Property<int>("Format")
                    .HasColumnType("INTEGER");

                b.Property<int>("ProgressPercent")
                    .HasColumnType("INTEGER");

                b.Property<string>("Quality")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .IsConcurrencyToken()
                    .HasColumnType("INTEGER");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("VideoTitle")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CreatedAt");

                b.HasIndex("Status", "ExpiresAt");

                b.ToTable("DownloadJobs", (string)null);
            });
#pragma warning restore 612, 618
    }
}

